name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.4.0
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        build_configuration: production
        base_href: ''
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/angular-sandbox

permissions:
  contents: write